version: "3"

networks:
  test-network:

services:
  db:
    image: mysql:8.0
    ports:
      - "21020:3306"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: test
      MYSQL_USER: test_user
      MYSQL_PASSWORD: test_pass
      MYSQL_ROOT_PASSWORD: test_pass_root
    volumes:
      - ./docker-compose/mysql/dump:/docker-entrypoint-initdb.d
      - ./docker-compose/mysql/conf:/etc/mysql/conf.d
      - ./docker-compose/mysql/mysql:/var/lib/mysql
    networks:
      - default
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db:db
    ports:
      - "21021:80"
    networks:
      - default
    environment:
      MYSQL_USER: test_user
      MYSQL_PASSWORD: test_pass_root
      MYSQL_ROOT_PASSWORD: test_pass_root
